name: poetry_project
tables:
  - name: authors
    columns:
      - name: name
        type: text
      - name: url
        type: text
        unique: true
    indexes:
      - name: author_name_index
        table: authors
        key: name

  - name: poems
    columns:
      - name: name
        type: text
      - name: url
        type: text
        unique: true
      - name: byline 
        type: text
      - name: author_id
        type: integer
    indexes:
      - name: author_name_index
        table: authors
        key: name
    foreign:
      - name: author_id
        table: authors
        key: id
